# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fausto's personal blog
description: >
  I am a web developer based in Berlin. I work for Memfault, where we create
  developer tools for firmware developers. I have a focus on front-end web
  development, but I'm trying to become a generalist.
author:
  name: Fausto Núñez Alberro
  link: https://github.com/fnune
  description: >
    I am a web developer based in Berlin. I work for Memfault, where we create
    developer tools for firmware developers. I have a focus on front-end web
    development, but I'm trying to become a generalist.
  email: fausto.nunez@mailbox.org
baseurl: "" # the subpath of your site, e.g. /blog
repository_url: "https://github.com/fnune/fnune.github.io"
url: "https://fnune.com" # the base hostname & protocol for your site

feed:
  path: atom.xml

# Build settings
plugins: [jekyll-sitemap, jekyll-autoprefixer, jekyll-feed]
markdown: kramdown
permalink: pretty

# Sass
sass:
  sass_dir: _scss
  style: :compressed

# Sitemap
sitemap:
  filename: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
      - "/css/screen.scss"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
